"use client"

// import type { Metadata } from "next"
import type React from "react"
import { Suspense } from "react"
import { Refine } from "@refinedev/core"
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar"
import routerProvider from "@refinedev/nextjs-router"
import { Provider } from "react-redux"

import "./globals.css"
import { authProviderClient } from "@/providers/auth-provider/auth-provider.client"
import { dataProvider } from "@/providers/data-provider"
import { store } from "@/store";

// export const metadata: Metadata = {
//   title: "Refine",
//   description: "Generated by create refine app",
//   icons: {
//     icon: "/favicon.ico",
//   },
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body>
          <Suspense>
            <RefineKbarProvider>
              <Refine
                routerProvider={routerProvider}
                authProvider={authProviderClient}
                dataProvider={dataProvider}
                resources={[
                  {
                    name: "dashboard",
                    list: "/dashboard",
                  },
                  // {
                  //   name: "blog_posts",
                  //   list: "/blog-posts",
                  //   create: "/blog-posts/create",
                  //   edit: "/blog-posts/edit/:id",
                  //   show: "/blog-posts/show/:id",
                  //   meta: {
                  //     canDelete: true,
                  //   },
                  // },
                  // {
                  //   name: "categories",
                  //   list: "/categories",
                  //   create: "/categories/create",
                  //   edit: "/categories/edit/:id",
                  //   show: "/categories/show/:id",
                  //   meta: {
                  //     canDelete: true,
                  //   },
                  // },
                ]}
                options={{
                  syncWithLocation: true,
                  warnWhenUnsavedChanges: true,
                  projectId: "6zlbqX-cY8J84-PvPF6c",
                }}
              >
                {children}
                <RefineKbar />
              </Refine>
            </RefineKbarProvider>
          </Suspense>
        </body>
      </html>
    </Provider>
  )
}
